number1 = int(input("Введите число номер 1: "))
number2 = int(input("Введите число номер 2: "))
number3 = int(input("Введите число номер 3: "))
number4 = int(input("Введите число номер 4: "))
print(number1*number2*number3*number4)